version: '3.8'
services:
  app:
    build:
      context:
        ../
      dockerfile:
        deploy/app.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres-database:
        condition: service_healthy
      redis-database:
        condition: service_healthy
    environment:
      DB_HOST: postgres-database
      DB_NAME: salut
      DB_USER: salut
      DB_PASSWORD: salut123
      REDIS_HOST: redis
    volumes:
      - ../../data/app:/app/cmd/log

  postgres-database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: salut
      POSTGRES_USER: salut
      POSTGRES_PASSWORD: salut123
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432" ]
      interval: 3s
      timeout: 3s
      retries: 5
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data

  redis-database:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ../../data/redis:/data
